import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Masthead } from '../components/masthead'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />

      <div className="z-0 px-12 py-16 text-2xl bg-white">
        <h2 className="mb-3 text-4xl font-bold">Lorem ipsum dolor sit amet.</h2>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure sed
          facere totam quibusdam dicta, atque fugit, eveniet nostrum asperiores
          esse nisi assumenda? Deserunt iusto nesciunt quo placeat, voluptates
          error eos?
        </p>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis
          assumenda ratione possimus placeat rem cumque? Vero natus omnis id
          accusantium corporis deleniti tempora quibusdam nostrum, quasi est
          expedita eaque quam?
        </p>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis
          assumenda ratione possimus placeat rem cumque? Vero natus omnis id
          accusantium corporis deleniti tempora quibusdam nostrum, quasi est
          expedita eaque quam?
        </p>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis
          assumenda ratione possimus placeat rem cumque? Vero natus omnis id
          accusantium corporis deleniti tempora quibusdam nostrum, quasi est
          expedita eaque quam?
        </p>
      </div>

      <footer className="flex justify-center py-8 bg-white border-t border-gray-200">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export default Home
